warning_threshold: 10

included:
  - Sources
  - Tests

colon:
  flexible_right_spacing: true

file_length:
  error: 600

function_body_length:
  warning: 100
  error: 350
  
indentation_width:
  indentation_width: 4
  include_comments: false

line_length: 
  warning: 160
  error: 260
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

# multiline_arguments:
#   first_argument_location: next_line
#   only_enforce_after_first_closure_on_first_line: true

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

type_body_length:
  warning: 400
  error: 450

vertical_whitespace:
  max_empty_lines: 2

identifier_name:
  min_length: 1

type_name:
  min_length: 2
  max_length: 70

large_tuple: 5
function_parameter_count: 6

force_cast: warning

cyclomatic_complexity:
  warning: 30 # two nested ifs are acceptable
  error: 90
  ignores_case_statements: true

nesting:
  type_level:
    warning: 3
    
disabled_rules:
  #- weak_delegate
  - multiple_closures_with_trailing_closure
  - opening_brace
  - trailing_comma
  - attributes
  - todo
  - multiline_function_chains
  - multiline_arguments
  
analyzer_rules:
  - unused_import
    
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - colon
  - comma_inheritance
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  # - multiline_arguments
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - toggle_bool
  - unavailable_condition
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_whitespace_closing_braces
  - yoda_condition
  - line_length
  - indentation_width

# lint-analyze:
# make clean
#     xcodebuild \
#     -project <YOUR_PROJECT>.xcodeproj \
#     -scheme <YOUR_SCHEME> \
#     -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.5' \
#     > xcodebuild.log
#     swiftlint analyze --fix --compiler-log-path xcodebuild.log --quiet
#     swiftlint lint --fix --format --quiet